<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>Test AlphaPrintToPDF</title>
</head>

<body>
<?php

include('AlphaPrintToPDF.php');

$data=array();
$data['pdfcreator']="My Company - 2007";
$data['file']="Default.pdf";

$data['data']['nom']="nom Dossier";
$data['data']['dossier']['nomdossier']="nom Dossier";
$data['data']['dossier']['numdossier']="125060";
$data['data']['enseigne']['nom']="Nom Enseigne";
$data['data']['dossier']['adresse1']="Adresse Ligne 1";
$data['data']['dossier']['adresse2']="Adresse Ligne 2";
$data['data']['dossier']['codepostal']="11111";
$data['data']['dossier']['ville']="Vile";
$data['data']['modele']['nomAff']="Page de Garde";
$data['data']['periode']="Janvier 2008 ˆ Decembre 2008";
$data['data']['user']['nom']="NAHAN";
$data['data']['user']['prenom']="Jean-Baptiste";
$data['data']['user']['tel']="04 26 23 02 71";
$data['data']['user']['fax']="04 26 23 02 89";
$data['data']['user']['email']="user@company.tld";
$data['data']['date']="17-03-2008";
$data['data']['elements']['0']="1 - page 1 page 1 page 1 page 1 page 1 page 1 page 1 page 1 page 1 page 1  1";
$data['data']['elements']['1']="2 - page 2 page 2 page 2 page 2 page 2 page 2 page 2 page 2";
$data['data']['elements']['2']="3 - page 3 page 3 page 3 page 3 page 3 page 3 page 3 page 3 page 3 page 3";
$data['data']['elements']['3']="4 - page 4 page 4 page 4 page 4 page 4";
$data['data']['elements']['4']="5 - page 5 page 5 page 5 page 5 page 5 page 5 page 5 page 5 page 5 page 5  5";
$data['data']['elements']['5']="6 - page 6 page 6 page 6 page 6 page 6 page 6 page 6 page 6 page 6";
$data['data']['elements']['6']="7 - page 7 page 7 page 7 page 7 page 7 page 7 page 7";
$data['data']['elements']['7']="8 - page 8 page 8 page 8 page 8 page 8 page 8 page 8 page 8 page 8 page 8";
/*$data['data']['']['']="";
$data['data']['']['']="";
$data['data']['']['']="";
$data['data']['']['']="";
$data['data']['']['']="";
$data['data']['']['']="";
$data['data']['']['']="";
$data['data']['']['']="";
$data['data']['']['']="";
$data['data']['']['']="";
$data['data']['']['']="";*/
$numLigne=0;
$data['data']['dataHeader'][$numLigne]['column1']="Col 1";
$data['data']['dataHeader'][$numLigne]['column2']="Col 2";
$data['data']['dataHeader'][$numLigne]['column3']="Col 3";
$data['data']['dataHeader'][$numLigne]['TypeLigne']="H";
$numLigne=0;
$data['data']['dataTableau'][$numLigne]['column1']="Data 1";
$data['data']['dataTableau'][$numLigne]['column2']="Data 2";
$data['data']['dataTableau'][$numLigne]['column3']="Data 3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";
$numLigne++;
$data['data']['dataTableau'][$numLigne]['column1']="Data ".$numLigne."1";
$data['data']['dataTableau'][$numLigne]['column2']="Data ".$numLigne."2";
$data['data']['dataTableau'][$numLigne]['column3']="Data ".$numLigne."3";
$data['data']['dataTableau'][$numLigne]['TypeLigne']="N";

$data['fontPath']='pdfGenerator/fonts/';
$data['keywords']='Test';
$data['Subject']='Test';
$data['Title']="Test Impression";
$data['Producer']=PDFPRODUCER;
$data['XMLFormatFile']="TestTableau.xmlpm";

//créer maintenant une instance de AlphaPrint

$aptPDF = & new AlphaPrintToPDF($data);

//affiche les message d'erreur si il y en a
if($aptPDF->error()) echo "Erreur lors de la creation du fichier : \n",$aptPDF->errorMsg();
else echo '<a href="',$data['file'],'" target="_Blank">Voir le fichier</a>';
?>


</body>
</html>
